baseURL: https://zecoo.github.io/hugo/
theme: hustrap
publishDir: "docs"
# theme: contrast-hugo
title: "玉子泡温泉"


params:
  sidebar:
    about: "This is the about part"
  description: "好记性不如烂笔头"

menus:
  sidebar:
  - name: "Link 1"
    url: "https://example.com"
  - name: "Link 2"
    url: "https://example.com"
  navbar:
    - about: ""