baseURL: https://zecoo.github.io/hugo/
theme: hustrap
publishDir: "docs"
# theme: contrast-hugo
title: "暴躁老农"


params:
  sidebar:
    board: "不会照搬其他博客，感谢参考的文章<br><br> Feel free to contact me~<br> wechat: doubleKon"
  description: "好记性也要烂笔头"

menus:
  sidebar:
  - name: "Douban"
    url: "https://www.douban.com/people/142240861/"
  - name: "Github"
    url: "https://github.com/zecoo"