baseURL: https://zecoo.github.io/hugo/
theme: hustrap
publishDir: "docs"
ignoreFiles:
  - '^content/files/.*\\.pdf$'
# theme: contrast-hugo
title: "张泽锟"


params:
  sidebar:
    board: "不会照搬其他博客，感谢提供参考的文章<br><br>有疑问可以联系我：<br>whu22kon[at]foxmail.com"
  description: "湖北·武汉"

menus:
  sidebar:
  - name: "Douban"
    url: "https://www.douban.com/people/142240861/"
  - name: "Github"
    url: "https://github.com/zecoo"
