baseURL: https://zecoo.github.io/hugo/
theme: hustrap
publishDir: "docs"
# theme: contrast-hugo
title: "玉子泡温泉"


params:
  sidebar:
    board: "不会照搬其他博客，参考文章很关键～<br><br> Feel free to contact me: <br> wechat: doubeKon"
  description: "好记性不如烂笔头"

menus:
  sidebar:
  - name: "Link 1"
    url: "https://example.com"
  - name: "Link 2"
    url: "https://example.com"
  navbar:
    - about: ""