
baseURL: "https://zecoo.github.io/hugo/"
languageCode: "en-us"
theme: "contrast-hugo"
publishDir: "docs"

menu:
  main:
  - {name: "Archive", url: "/", identifier: "home", weight: 1}
  - {name: "About", url: "/about/", identifier: "about", weight: 2}
  - {name: "Demo", url: "/demo/", identifier: "demo", weight: 6}
  remote:
  - {name: "Douban", url: "", identifier: "weibo", weight: 3}
  - {name: "Github", url: "https://github.com/zecoo", identifier: "github", weight: 4}
  - {name: "Subscribe", url: "/index.xml", identifier: "rss", weight: 5}